### ISSUE TITLE
[NetStandard] - Target NetStandard

### ISSUE THREAD

**Issue by deinok** [editorconfig/editorconfig-core-net#2]

**Comment by Mpdreamz** [comment]
Resolved by #9 and subsequent commits. Thanks for reporting @deinok 👍

**Comment by EwanNoble** [comment]
Apologies for commenting on a closed issue, when will this be making it's way to nuget?

**Comment by Mpdreamz** [comment]
Appreciate the nudge! Will get on it next week

**Comment by LordMike** [comment]
Nudgy.. :)
